version: '3'

services:
    flask-api:
        build: .
        ports:
            - "5000:5000"
        depends_on: 
            - mysqlsrv
        networks: 
            - flask-api-network
    mysqlsrv:
        image: mysql:5.7.31
        environment: 
            MYSQL_ROOT_PASSWORD: senhasecreta
            MYSQL_DATABASE: flask_api
        ports:
            - "3307:3306"
        volumes:
            - db-mysql:/var/lib/mysql
        networks: 
            - flask-api-network
networks: 
    flask-api-network:
        driver: bridge

volumes:
    db-mysql: