version: '3'

services:
    mysqlsrv:
        image: mysql:5.7
        environment: 
            MYSQL_ROOT_PASSWORD: "senhasecreta"
        ports:
            - "3306:3306"
        volumes:
            - db_mysql:/var/lib/mysql

volumes:
    db_mysql: