"""empty message

Revision ID: ea92dbad61b5
Revises: 904ffd8aa3e7
Create Date: 2020-07-26 19:59:16.902500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea92dbad61b5'
down_revision = '904ffd8aa3e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto', sa.Column('valor', sa.Float(precision=2), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produto', 'valor')
    # ### end Alembic commands ###
